import Head from "next/head";
import Link from "next/link";
import { Tab } from "@headlessui/react";
import Masonry from "react-masonry-css";
// import { Span } from "next/dist/trace";
import classNames from "classnames";

import Image from "next/image";

import coco from "../public/Coco.png";
import gummigoo from "../public/gummigoo.png";
import incineroar from "../public/incineroar-lifting-banjo.png";
import iirl from "../public/iirl-bday-illustration.png";
import wendell from "../public/wendell-chupete.png";
import sheeb from "../public/sheeb-bday-card.png";

import type { LightGallery } from "lightgallery/lightgallery";
import LightGalleryComponent from "lightgallery/react";

import "lightgallery/css/lightgallery.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lg-thumbnail.css";

import lgThumbnail from "lightgallery/plugins/thumbnail";
import lgZoom from "lightgallery/plugins/zoom";
import { useRef } from "react";

const tabs = [
  {
    key: "all",
    display: "All"
  },
  {
    key: "characters",
    display: "Characters"
  },
  {
    key: "backgrounds",
    display: "Backgrounds"
  }
]

const images = [
  coco,
  gummigoo,
  incineroar,
  iirl,
  wendell,
  sheeb
]

export default function Home() {

  const lightboxRef = useRef<LightGallery | null>(null);

  return (
    <>
      <div className="h-full bg-stone-950 bg-bottom bg-cover overflow-auto">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
        <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
          <div className="uppercase text-lg font-weight-400">
            Art Portfolio
          </div>
          <Link href="#" className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90">
              Get in touch
          </Link>
        </header>

        <main className="pt-[110px]">
          <div className="flex flex-col items-center h-full">
            {/* Tabs in whcih the drawings will go */}
            <Tab.Group>
              <Tab.List className="flex items-center gap-12">

                {tabs.map((tab) => (
                  <Tab key={tab.key} className="p-2">
                    {({selected}) => (
                      <span className={classNames(
                        "uppercase text-sm cursor-pointer", 
                        selected ? "text-white" : "text-stone-600")}>
                        {tab.display}
                      </span>
                    )}
                  </Tab>
                ))}
              </Tab.List>
              <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
                <Tab.Panel >
                  <Masonry breakpointCols={2} className="flex gap-4" columnClassName="">
                      {images.map((image, index) => (
                        <Image 
                        key={image.src} 
                        src={image} 
                        alt="placeholder" 
                        className="my-4 hover:opacity-70 hover:cursor-pointer" 
                        placeholder="blur"
                        onClick={() => {
                          lightboxRef.current?.openGallery(index);
                        }}
                        />
                      ))}

                  </Masonry>
                  <LightGalleryComponent
                    onInit={(ref) => {
                      if (ref) {
                        lightboxRef.current = ref.instance;
                      }
                    }}
                    speed={500}
                    plugins={[lgThumbnail, lgZoom]}
                    dynamic
                    dynamicEl={images.map((image) => ({
                      src: image.src,
                      thumb: image.src
                    }))}
                    />
                </Tab.Panel>
                <Tab.Panel>
                  
                </Tab.Panel>
                <Tab.Panel>
                  
                </Tab.Panel>
              </Tab.Panels>
            </Tab.Group>
          </div>
        </main>

        <footer className="h-[90px] flex justify-center items-center uppercase text-lg font-medium">
          <p>placeholder for footer</p>
        </footer>
      </div>
    </>
  );
}
