import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
import Link from "next/link";
import { Tab } from "@headlessui/react";
import Masonry from "react-masonry-css";
// import { Span } from "next/dist/trace";

const tabs = [
  {
    key: "all",
    display: "All"
  },
  {
    key: "characters",
    display: "Characters"
  },
  {
    key: "backgrounds",
    display: "Backgrounds"
  }
]

export default function Home() {
  return (
    <>
      <div className="flex flex-col h-full bg-stone-950 bg-bottom bg-cover">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
        <header className="flex justify-between items-center h-[90px] px-6">
          <div>Art Portfolio</div>
          <Link href="#" className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90">
              Get in touch
          </Link>
        </header>

        <main className="grow">
          <div className="flex flex-col items-center h-full">
            {/* Tabs in whcih the drawings will go */}
            <Tab.Group>
              <Tab.List className="flex items-center gap-12">

                {tabs.map((tab) => (
                  <Tab key={tab.key} className="p-2">
                    {({selected}) => (
                      <span className={selected ? "text-white" : "text-stone-600"}>
                        {tab.display}
                      </span>
                    )}
                  </Tab>
                ))}
              </Tab.List>
              <Tab.Panels className="bg-stone-900 bg-opacity-80 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
                <Tab.Panel >
                  <Masonry className="" columnClassName="">
                    {/* Here is where my drawings go */}
                      <img src="" alt="" />
                  </Masonry>
                </Tab.Panel>
                <Tab.Panel>
                  
                </Tab.Panel>
                <Tab.Panel>
                  
                </Tab.Panel>
              </Tab.Panels>
            </Tab.Group>
          </div>
        </main>

        <footer className="h-[60px] flex justify-center items-center">
          <p>placeholder for footer</p>
        </footer>
      </div>
    </>
  );
}
